chore: polkadot-v0.9.15
galacticcouncil/HydraDX-node pull request #355
Opened 2022-01-25 09:27 UTC by enthusiastmartin

2022-01-26 18:45 UTC, lumir-mrkva requested changes

2022-01-26 18:45 UTC, lumir-mrkva commented on runtime/testing-hydradx/Cargo.toml
> +version = "101.0.1"
```suggestion
version = "102.0.0"
```

2022-01-26 18:45 UTC, lumir-mrkva commented on runtime/hydradx/Cargo.toml
> +version = "101.0.1"
```suggestion
version = "102.0.0"
```

2022-01-26 18:46 UTC, lumir-mrkva commented
bump `hydra-dx-build-script-utils`

2022-01-26 18:50 UTC, lumir-mrkva commented
inclusion and upgrade tests can be fixed by bumping polkadot-launch version to ^2.1.0 and correctly specifying para id (it is 200 now)

2022-01-26 21:09 UTC, enthusiastmartin commented
> bump `hydra-dx-build-script-utils`

well, cannot do.  that's not really part of this branch. it is taken from the master branch which is odd.  Not sure why it is done like that. 

i will sort it out.

2022-01-27 08:09 UTC, enthusiastmartin commented
> build depends on #356

already cherry picked the change as it was not possible to merge.

2022-01-27 10:52 UTC, lumir-mrkva approved these changes

2022-01-27 10:52 UTC, merged