Fix/ami image
galacticcouncil/HydraDX-node pull request #356
Opened 2022-01-25 13:21 UTC by fakirAyoub

Update AMI image with valid token

2022-01-26 18:31 UTC, lumir-mrkva requested changes

2022-01-26 18:31 UTC, lumir-mrkva commented on .github/workflows/tests.yml
> +  push:
dont trigger workflow on push

2022-01-26 18:32 UTC, lumir-mrkva commented
also the pr has to semantically named https://github.com/zeke/semantic-pull-requests

2022-01-26 18:51 UTC, lumir-mrkva commented on .github/workflows/tests.yml
> +  push:
@fakirAyoub this is still an issue

2022-01-30 14:37 UTC, fakirAyoub commented on .github/workflows/tests.yml
> +  push:
@lumir-mrkva change done

2022-01-30 15:05 UTC, lumir-mrkva approved these changes

2022-01-30 15:06 UTC, merged