chore: upgrate to polkadot-0.9.26
galacticcouncil/HydraDX-node pull request #428
Opened 2022-07-28 20:00 UTC by Roznovjak

2022-08-08 19:58 UTC, lumir-mrkva commented
Task linked: [CU-2p79uye Upgrade to polkadot-v0.9.26](https://app.clickup.com/t/2p79uye)

2022-09-16 13:24 UTC, lumir-mrkva requested changes

2022-09-22 11:19 UTC, Roznovjak commented on node/src/rpc.rs
> +	if let Some(command_sink) = command_sink {
no, removed

2022-09-30 13:47 UTC, Roznovjak commented
Closing in favor of #463

2022-09-30 13:47 UTC, closed without merging