refactor: tx multi payment pallet
galacticcouncil/HydraDX-node pull request #713
Opened 2023-12-08 09:09 UTC by enthusiastmartin

2023-12-20 13:12 UTC, mrq1911 commented on pallets/transaction-multi-payment/src/lib.rs
> +		T::NativeAssetId::get()
default currency is different for EVM accounts, they have WETH

2023-12-20 13:12 UTC, mrq1911 commented on pallets/transaction-multi-payment/src/lib.rs
>  		pub fn set_currency(origin: OriginFor<T>, currency: AssetIdOf<T>) -> DispatchResult {
EVM account cannot change payment currency from default

2023-12-20 13:15 UTC, mrq1911 commented on pallets/transaction-multi-payment/src/lib.rs
> +	pub type AccountCurrency<T: Config> =
this is major change that breaks API

2023-12-20 13:15 UTC, mrq1911 commented on pallets/transaction-multi-payment/src/lib.rs
> +	pub type AcceptedCurrencies<T: Config> = StorageMap<_, Twox64Concat, AssetIdOf<T>, (), OptionQuery>;
this breaks API as well

2023-12-20 13:24 UTC, mrq1911 requested changes

2023-12-20 13:24 UTC, mrq1911 commented on runtime/hydradx/src/system.rs
> +	type PriceProvider = OmnipoolSpotPriceProvider<Runtime>;
with this we support only assets that are in omnipool as payment assets, we should support every asset we have price for in oracle and aditionally even new assets that dont have any price in oracle yet (till shitcoin casino)

2023-12-22 15:07 UTC, apopiak reviewed
I guess you were planning to remove the comments later, so I stopped pointing them out at some point ^^

2023-12-22 15:07 UTC, apopiak commented on runtime/adapters/src/lib.rs
> +		//let converted_fee = price.checked_mul_int(fee).ok_or(XcmError::Overflow)?;
commented code

2023-12-22 15:07 UTC, apopiak commented on runtime/adapters/src/lib.rs
> +			//let converted_fee = price.saturating_mul_int(fee).saturated_into();
comment

2023-12-22 15:07 UTC, apopiak commented on runtime/adapters/src/lib.rs
> +			//pallet_transaction_multi_payment::Pallet::<P>::get_currency_price(currency.into())
comment

2024-04-20 09:27 UTC, enthusiastmartin commented
closing this..due to recent changes in multi payment pallet - this refactor is no longer possible, or hard to re-refactor.

2024-04-20 09:27 UTC, closed without merging