feat: evm permit
galacticcouncil/HydraDX-node pull request #795
Opened 2024-03-27 11:08 UTC by enthusiastmartin

2024-04-11 12:33 UTC, mrq1911 requested changes

2024-04-11 12:33 UTC, mrq1911 commented on rococo-local/config-zombienet.json
> +          "command": "/home/martin/workspace/galactic/HydraDX-node/target/release/hydradx",
these changes are not intended probably

2024-04-11 12:33 UTC, mrq1911 commented on runtime/hydradx/src/evm/permit.rs
> +			precompiles::DISPATCH_ADDR,
we should support permit calls for other contracts as well

2024-04-11 12:33 UTC, mrq1911 commented on pallets/transaction-multi-payment/src/lib.rs
> +				None,
why is nonce handled differently?

2024-04-11 12:33 UTC, mrq1911 commented on pallets/transaction-multi-payment/src/lib.rs
> +			currency: AssetIdOf<T>,
thinking more about it this lets dispatcher to change payment currency without your approval. best would be to require user to call set_currency (though permit) 1st to change it same as we do with regular set_currency. regular evm call interaction with RPC (not permit) would always charge WETH. ofc the evm calls incoming from extrinsics would behave the same as they cuirrenctly are to enable substrate users to pay in any currency

2024-04-11 12:33 UTC, mrq1911 commented on pallets/transaction-multi-payment/src/lib.rs
> +		pub fn dispatch_permit(
where is nonce?

2024-04-11 12:33 UTC, mrq1911 commented on runtime/hydradx/src/evm/permit.rs
> +		input: Vec<u8>,
this param should be called 'data' for consistency

2024-04-19 15:21 UTC, enthusiastmartin commented on precompiles/call-permit/src/lib.rs
> +		3_000 // cost of ECRecover precompile for reference
this comes from moonbeam, i dont want tochange anything in there

2024-04-19 15:21 UTC, enthusiastmartin commented on precompiles/call-permit/src/tests.rs
> +				.expect_cost(0) // TODO: Test db read/write costs
their tests

2024-04-19 15:21 UTC, enthusiastmartin commented on precompiles/call-permit/src/tests.rs
> +// // This test checks the validity of a metamask signed message against the permit precompile
not other code

2024-04-23 19:17 UTC, mrq1911 requested changes
happened handler implementation in transaction multipayment should set default currency same for evm accounts

2024-04-23 19:17 UTC, mrq1911 commented on runtime/hydradx/src/system.rs
> +	//type TryCallCurrency = pallet_transaction_multi_payment::TryCallCurrency<Runtime>;
delete

2024-04-29 12:28 UTC, mrq1911 approved these changes
ready for testing and UI impl

for production we need https://github.com/galacticcouncil/HydraDX-node/issues/814

2024-04-29 13:25 UTC, merged